# Azure Pipelines YAML file for Cypress API Automation

# Define the pipeline trigger
trigger:
- main

# Define the pool of agents to use
pool:
  vmImage: 'ubuntu-latest'

# Define the stages of the pipeline
stages:
- stage: test
  displayName: 'Run Cypress API tests'
  jobs:
  - job: cypress
    displayName: 'Run Cypress tests'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '14.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm install -g cypress
      displayName: 'Install Cypress'
    - script: |
        cypress run --spec 'cypress/integration/api/*.spec.js'
      displayName: 'Run Cypress API tests'
    
   - task: PublishBuildArtifacts@1
  displayName: 'Publish Web Artifact'
  inputs:
    PathtoPublish: '$(Build.BinariesDirectory)/$(Build.BuildId)'
    ArtifactName: 'drop-$(Build.BuildId)'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish ARM Artifact'
  inputs:
    PathtoPublish: 'deploy/'
    ArtifactName: 'drop-arm'
    publishLocation: 'Container'
