orbs:
  cypress: cypress-io/cypress@1.2.3

jobs:
  build:
    working_directory: ~/Desktop/projects/backend-automation
    docker:
      - image: cypress/base:14.17.0
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - cypress/run:
          command: run --spec "cypress/integration/api/*.spec.js"
          start: npm start
          env:
            API_URL: http://localhost:3000/api

workflows:
  main:
    jobs:
      - build