name: Cypress Tests and Deployment

on:
  push:
    branches:
      - main

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run cypress:run

      - name: Archive Test Reports
        uses: actions/upload-artifact@v2
        with:
          name: Test Reports
          path: cypress/reports

  deploy:
    needs: cypress-tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.email "zeeshan.ali@invozone.com"
          git config --global user.name "zeeshanali877"
          npm run deploy

